### ISSUE TITLE
route

### ISSUE THREAD

**Issue by joehua87** [buzzcms/buzzcms#5]
Store data for frontend route
Example, posts page will have the follow:
```yaml
pattern: /blog
heading:
  title: Blog
  subtitle: Awesome posts about ...
seo:
  title: Post
  description: This is the post page description
paging:
  limit: 24
# Use to generate sitemap
sitemap:
  enabled: true
  changefreq: weekly
  priority: 0.1
  filter:
    state:
      eq: published
    entryTypeCode:
      eq: post
```
